// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types manually

export type Database = {
  public: {
    Tables: {
      moods: {
        Row: {
          mood_id: number;
          mood_name: string;
          mood_emoji: string | null;
          mood_color: string | null;
          mood_description: string | null;
        };
        Insert: {
          mood_id?: number;
          mood_name: string;
          mood_emoji?: string | null;
          mood_color?: string | null;
          mood_description?: string | null;
        };
        Update: {
          mood_id?: number;
          mood_name?: string;
          mood_emoji?: string | null;
          mood_color?: string | null;
          mood_description?: string | null;
        };
      };
      entries: {
        Row: {
          entry_id: number;
          user_id: string;
          mood_id: number;
          entry_text: string;
          entry_date: string;
          entry_time: string;
          created_at: string;
          updated_at: string;
          is_deleted: boolean;
        };
        Insert: {
          entry_id?: number;
          user_id: string;
          mood_id: number;
          entry_text: string;
          entry_date: string;
          entry_time: string;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
        Update: {
          entry_id?: number;
          user_id?: string;
          mood_id?: number;
          entry_text?: string;
          entry_date?: string;
          entry_time?: string;
          created_at?: string;
          updated_at?: string;
          is_deleted?: boolean;
        };
      };
      media_files: {
        Row: {
          media_id: number;
          entry_id: number;
          file_name: string;
          file_type: string;
          media_category: "image" | "audio" | "video";
          base64_data: string;
          uploaded_at: string;
        };
        Insert: {
          media_id?: number;
          entry_id: number;
          file_name: string;
          file_type: string;
          media_category: "image" | "audio" | "video";
          base64_data: string;
          uploaded_at?: string;
        };
        Update: {
          media_id?: number;
          entry_id?: number;
          file_name?: string;
          file_type?: string;
          media_category?: "image" | "audio" | "video";
          base64_data?: string;
          uploaded_at?: string;
        };
      };
    };
  };
};

